import Login from "./login";
import Head from 'next/head'

export default function Home() {
    return (
        <div>
            <Head>
                <title>Test App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <Login/>
            </main>

            <footer>
            </footer>
        </div>
    )
}
